endpoints:
  - name: Nginx
    group: QNAS
    url: "https://celery.loafclan.org/"
    interval: 1m
    conditions:
      - "[STATUS] == 403"
      - "[RESPONSE_TIME] < 1000"

  - name: Gatus Page
    group: External
    url: "https://celery.loafclan.org/status"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"

  - name: Blockbust-Web
    group: Blockbust™
    url: "https://celery.loafclan.org/bbtm/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"

  - name: Blockbust-Glances
    group: Blockbust™
    url: "https://celery.loafclan.org/bbtm-glances/"
    interval: 1m
    conditions:
      - "[STATUS] == 401"
      - "[RESPONSE_TIME] < 1000"

  - name: QNAS-Glances
    group: QNAS
    url: "https://celery.loafclan.org/qnas-glances/"
    interval: 1m
    conditions:
      - "[STATUS] == 401"
      - "[RESPONSE_TIME] < 1000"

  - name: Syncplay
    group: QNAS
    url: "tcp://sync.loafclan.org:8999"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
